apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webappdemo-argo-application
  namespace: argocd
  annotations:
    
    
    argocd-image-updater.argoproj.io/allocation.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: "kustomization:/k8s"
    argocd-image-updater.argoproj.io/git-branch: main:image-updater-{{.SHA256}}
spec:
  project: default

  source:
    repoURL: https://github.com/JagdevMishraWK/ShoppingWeb.git
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: webappdemo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
