apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webappdemo-argo-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: ghcr.io/ShoppingWeb
    argocd-image-updater.argoproj.io/alias.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/alias.update-strategy: latest
spec:
  project: default

  source:
    repoURL: https://github.com/JagdevMishraWK/ShoppingWeb.git
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: webappdemo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
