apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdemo
  labels:
    app: webappdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webappdemo
  template:
    metadata:
      labels:
        app: webappdemo
    spec:
      containers:
        - name: webappdemo
          image: 943725333913.dkr.ecr.eu-west-1.amazonaws.com/mywebapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
