apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdemo
  labels:
    app: webappdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webappdemo
  template:
    metadata:
      labels:
        app: webappdemo
    spec:
      containers:
        - name: webappdemo
          image: 943725333913.dkr.ecr.eu-west-1.amazonaws.com/mywebapp@sha256:c30e733d61e140520feb3baf42e24116256ab0f26dba4deab57dea436c52cacc
          imagePullPolicy: Always
          ports:
            - containerPort: 80
